
// This file is generated by the examples-index command. Please do not edit
// manually, or your changes will be overwritten.

export { default as LinkedSliders } from '../src/components/Slider/examples/LinkedSliders.js'
